import { notFound } from 'next/navigation'
import { db } from '@/lib/server/store'
import { observations } from '@/lib/server/pipeline'
import { SPECIES_BY_KEY } from '@/lib/science/species'
import ReportPlates from './ReportPlates'
import PrintButton from './PrintButton'
import Logo from '@/components/brand/Logo'
import { Breadcrumbs } from '@/components/app/ui'

export const metadata = { title: 'Run report' }

export default async function Report({ params }: PageProps<'/app/runs/[id]/report'>) {
  const { id } = await params
  const s = db()
  const run = s.runs.find((r) => r.id === id)
  if (!run) notFound()
  const p = s.protocols.find((x) => x.id === run.protocolId)!
  const d = s.devices.find((x) => x.id === run.deviceId)!
  const obs = observations(run)
  const who = (u?: string) => s.users.find((x) => x.id === u)?.name ?? u ?? '—'
  const Ts = run.env.filter((e) => e.h > 1).map((e) => e.T)
  const meanT = Ts.reduce((a, b) => a + b, 0) / Math.max(1, Ts.length)
  const rows = obs.dishes.map((dd) => {
    const dish = run.dishes.find((x) => x.position === dd.position)!
    const smp = s.samples.find((x) => x.id === dish.sampleId)!
    const last = dd.frames[dd.frames.length - 1]
    const by: Record<string, number> = {}
    for (const c of last?.colonies ?? []) by[c[4]] = (by[c[4]] ?? 0) + 1
    return { pos: dd.position, smp, n: last?.colonies.length ?? 0, by, cov: last?.coverage ?? 0, cols: last?.colonies ?? [] }
  })
  return (
    <>
    <div className="border-b border-line bg-white px-5 py-4 sm:px-8 print:hidden">
      <Breadcrumbs crumbs={[{ href: '/app', label: 'Overview' }, { href: '/app/runs', label: 'Runs' }, { href: `/app/runs/${run.id}`, label: run.name }, { label: 'Report' }]} />
    </div>
    <div className="mx-auto max-w-[900px] bg-white px-5 py-10 text-[13px] sm:px-10 print:px-0 print:py-0">
      <div className="flex items-start justify-between border-b-2 border-ink pb-5">
        <div><Logo className="h-7 text-[18px]" /><div className="mt-4 font-mono text-[24px] font-semibold">{run.name}</div><div className="text-muted">Culture imaging report · {run.id}</div></div>
        <div className="text-right font-mono text-[12px] leading-5"><div>{d.name} · {d.serial}</div><div>Firmware {d.firmware}</div><div>Generated {new Date().toLocaleString('en-GB')}</div><PrintButton /></div>
      </div>
      <div className="mt-6 grid grid-cols-4 gap-4 font-mono text-[12px]">
        {[['Protocol', p.name], ['Medium', p.medium], ['Setpoint', `${p.tempC} °C · ${p.rh}% RH`], ['Duration', `${run.elapsedH.toFixed(0)} / ${p.durationH} h`],
          ['Mean chamber T', `${meanT.toFixed(2)} °C`], ['Image sets', String(run.captures.length)], ['Operator', who(run.operatorId)],
          ['Review', run.review.status === 'pending' ? 'Pending' : `${run.review.status} — ${who(run.review.by)}`]].map(([k, v]) => (
          <div key={k}><div className="text-[10.5px] uppercase tracking-wider text-muted">{k}</div><div className="mt-0.5 font-semibold">{v}</div></div>
        ))}
      </div>
      <ReportPlates plates={rows.map((r) => ({ pos: r.pos, label: r.smp.label, cols: r.cols }))} />
      <table className="mt-6 w-full border-collapse text-left">
        <thead><tr className="border-b border-ink font-mono text-[10.5px] uppercase tracking-wider">{['Pos', 'Barcode', 'Sample', 'Source', 'Colonies', 'Coverage', 'Presumptive composition'].map((h) => <th key={h} className="py-2 pr-3">{h}</th>)}</tr></thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.pos} className="border-b border-line align-top">
              <td className="py-2 pr-3 font-mono">{r.pos}</td><td className="py-2 pr-3 font-mono">{r.smp.barcode}</td><td className="py-2 pr-3">{r.smp.label}</td><td className="py-2 pr-3 capitalize">{r.smp.source}</td>
              <td className="py-2 pr-3 font-mono">{r.n}</td><td className="py-2 pr-3 font-mono">{(r.cov * 100).toFixed(1)}%</td>
              <td className="py-2 pr-3 italic">{Object.entries(r.by).sort((a, b) => b[1] - a[1]).map(([k, n]) => `${SPECIES_BY_KEY[k]?.name ?? k} (${n})`).join(', ') || '—'}</td>
            </tr>
          ))}
        </tbody>
      </table>
      {run.review.note && <div className="mt-6 rounded-lg bg-paper p-4"><div className="font-mono text-[10.5px] uppercase tracking-wider text-muted">Reviewer note</div><div className="mt-1">{run.review.note}</div></div>}
      <div className="mt-8 border-t border-line pt-4 text-[11px] leading-5 text-muted">
        Presumptive identifications are generated by a simulated classifier in this demonstration environment and are not diagnostic. Colony growth is simulated with the
        Cardinal Model with Inflection (Rosso et al., 1993) on the logged chamber temperature. Confirm identifications with standard mycological methods.
      </div>
    </div>
    </>
  )
}
